create table public."IPT_在庫保管手数料情報" (
  "ASIN" character varying(20)
  , fnsku character varying(20)
  , "商品名" character varying(20)
  , "Fulfillment center" character varying(20)
  , "Country code" character varying(20)
  , "Longest side" character varying(20)
  , "Median side" character varying(20)
  , "Shortest side" character varying(20)
  , "Measurement units" character varying(20)
  , weight character varying(20)
  , "Weight units" character varying(20)
  , "Item volume" character varying(20)
  , "Volume units" character varying(20)
  , "Product size tier" character varying(20)
  , "Average quantity on hand" character varying(20)
  , "Average quantity pending removal" character varying(20)
  , "Total item volume (est.)" character varying(20)
  , "Month of charge" character varying(20)
  , "Storage rate" character varying(20)
  , "通貨" character varying(20)
  , "Monthly storage fee (est.)" character varying(20)
  , category character varying(20)
  , "Total Incentive Amount" character varying(20)
  , breakdown_incentive_fee_amount character varying(20)
  , average_quantity_customer_orders character varying(20)
  , "店舗ID" character varying(20)
  , "登録日時" character varying(20)
  , "更新日時" character varying(20)
);
