create table public."IPT_長期在庫保管手数料請求額情報" (
  "日付" character varying(20)
  , "出品者SKU" character varying(20)
  , "FNSKU" character varying(20)
  , "ASIN" character varying(20)
  , "商品名" character varying(20)
  , "コンディション" character varying(20)
  , "qty-charged-long-time-range-long-term-storage-fee" character varying(20)
  , "商品サイズ" character varying(20)
  , "通貨" character varying(20)
  , "long-time-range-long-term-storage-fee" character varying(20)
  , "qty-charged-short-time-range-long-term-storage-fee" character varying(20)
  , "short-time-range-long-term-storage-fee" character varying(20)
  , "volume-unit" character varying(20)
  , "国" character varying(20)
  , "enrolled-in-small-and-light" character varying(20)
  , "店舗ID" character varying(20)
  , "登録日時" character varying(20)
  , "更新日時" character varying(20)
);
