create table public."IPT_返送所有権放棄依頼詳細情報" (
  "依頼日" character varying(20)
  , "依頼番号" character varying(20)
  , "依頼のタイプ" character varying(20)
  , "依頼のステータス" character varying(20)
  , "更新日" character varying(20)
  , "出品者SKU" character varying(20)
  , "FNSKU" character varying(20)
  , "商品のステータス" character varying(20)
  , "依頼した数" character varying(20)
  , "キャンセルした数" character varying(20)
  , "廃棄した数" character varying(20)
  , "発送した数" character varying(20)
  , "処理中の数" character varying(20)
  , "返送/廃棄手数料" character varying(20)
  , "通貨" character varying(20)
  , "店舗ID" character varying(20)
  , "登録日時" character varying(20)
  , "更新日時" character varying(20)
);
