create table public."IPT_ペイメント情報 " (
"日付/時間" character varying(20),
"決済番号" character varying(20),
"トランザクションの種類" character varying(20),
"注文番号" character varying(50),
"SKU" character varying(20),
"説明" character varying(20),
"数量" character varying(20),
"Amazon 出品サービス" character varying(20),
"フルフィルメント1" character varying(20),
"市町村1" character varying(20),
"都道府県1" character varying(20),
"郵便番号1" character varying(20),
"税金徴収型1" character varying(20),
"商品売上1" character varying(20),
"商品の売上税" character varying(20),
"配送料" character varying(20),
"配送料の税金" character varying(20),
"ギフト包装手数料" character varying(20),
"ギフト包装クレジットの税金" character varying(20),
"Amazon1ポイントの費用" character varying(20),
"プロモーション割引額" character varying(20),
"プロモーション割引の税金" character varying(20),
"源泉徴収税を伴うマーケットプレイス" character varying(20),
"手数料" character varying(20),
"FBA 手数料1" character varying(20),
"トランザクションに関するその他の手数料" character varying(20),
"その他" character varying(20),
"合計" character varying(20),
"Amazon2 出品サービス" character varying(20),
"フルフィルメント2" character varying(20),
"市町村2" character varying(20),
"都道府県2" character varying(20),
"郵便番号2" character varying(20),
"税金徴収型" character varying(20),
"商品売上" character varying(20),
"商品の売上税2" character varying(20),
"配送料2" character varying(20),
"配送料の税金2" character varying(20),
"ギフト包装手数料2" character varying(20),
"ギフト包装クレジットの税金2" character varying(20),
"Amazon3ポイントの費用 " character varying(50),
"プロモーション割引額2" character varying(20),
"プロモーション割引の税金2" character varying(20),
"源泉徴収税を伴うマーケットプレイス2" character varying(20),
"手数料2" character varying(20),
"FBA 手数料" character varying(20),
"トランザクションに関するその他の手数料2" character varying(20),
"その他2" character varying(20),
"合計2" character varying(20)

  
  , "店舗ID" character varying(20)
  , "登録日時" character varying(20)
  , "更新日時" character varying(20)
);
