create table public."HIS_’·ŠúİŒÉ•ÛŠÇè”—¿¿‹Šúî•ñ" (
  "“ú•ô" character varying(50)
  , "ï•éÒSKU" character varying(50)
  , "FNSKU" character varying(50)
  , "ASIN" character varying(50)
  , "¤•é–¼" character varying(200)
  , "ƒÒƒ“ƒæƒÂƒÖƒ‡ƒ“" character varying(50)
  , "qty-charged-long-time-range-long-term-storage-fee" character varying(50)
  , "¤•éƒÔƒÃƒÙ" character varying(50)
  , "’Ê‰İ" character varying(50)
  , "long-time-range-long-term-storage-fee" character varying(50)
  , "qty-charged-short-time-range-long-term-storage-fee" character varying(50)
  , "short-time-range-long-term-storage-fee" character varying(50)
  , "volume-unit" character varying(50)
  , "‘" character varying(50)
  , "enrolled-in-small-and-light" character varying(50)
  , "“Ø•ÜID" character varying(20)
  , "“ï˜Ş“ú" character varying(20)
  , "ØÖ“ú" character varying(20)
);