create table public."IPT_ƒòƒ×ƒìƒØƒŒƒüÛƒç-1" (
  "“ú•ô" character varying(20)
  , "’•¶¤•é”„ã" character varying(20)
  , "’•¶¤•é”„ã-B2B" character varying(20)
  , "’•¶‚³‚ê‚½¤•é“ß”" character varying(20)
  , "’•¶‚³‚ê‚½¤•é“ß” - B2B" character varying(20)
  , "’•¶•é–Ú‘”" character varying(20)
  , "’•¶•é–Ú‘” - B2B" character varying(20)
  , "•é–Ú‚ ‚½‚è‚Ì•½‹Ï”„ã" character varying(20)
  , "•é–Ú‚ ‚½‚è‚Ì•½‹Ï”„ã - B2B" character varying(20)
  , "•é–Ú‚ ‚½‚è‚Ì•½‹Ï“ß”" character varying(20)
  , "•é–Ú‚ ‚½‚è‚Ì•½‹Ï“ß” - B2B" character varying(20)
  , "•½‹Ï”„‰¿" character varying(20)
  , "•½‹Ï”„‰¿ - B2B" character varying(20)
  , "ƒÚƒâƒÖƒ‡ƒ“ - ‡Œö" character varying(20)
  , "ƒÚƒâƒÖƒ‡ƒ“-‡Œö-B2B" character varying(20)
  , "’•¶•é–Ú”ƒÚƒâƒÖƒ‡ƒ“”ä—¦" character varying(20)
  , "’•¶•é–Ú”ƒÚƒâƒÖƒ‡ƒ“”ä—¦ - B2B" character varying(20)
  , "•½‹Ïï•é”" character varying(20)
  , "“Ø•ÜID" character varying(20)
  , "“ï˜Ş“ú" character varying(20)
  , "ØÖ“ú" character varying(20)
);