create table public."IPT_•Ô•éî•ñ" (
  "•Ô•é“ú" character varying(50)
  , "’•¶”Ô†" character varying(50)
  , "ï•éÒSKU" character varying(50)
  , "ASIN" character varying(50)
  , "FNSKU" character varying(50)
  , "¤•é–¼" character varying(200)
  , "”—Ê" character varying(50)
  , "FC" character varying(50)
  , "¤•é‚Ìó‘Ô" character varying(50)
  , "——Ò" character varying(50)
  , lpn character varying(50)
  , "‚¨‹ñ—ì‚ÌƒÒƒƒ“ƒç" character varying(200)
  , "“Ø•ÜID" character varying(20)
  , "“ï˜Ş“ú" character varying(20)
  , "ØÖ“ú" character varying(20)
);