create table public."IPT_•Ô‘—Š—ÌŒ •úŠüˆË—ŠÚ×î•ñ" (
  "ˆË—Š“ú" character varying(50)
  , "ˆË—Š”Ô†" character varying(50)
  , "ˆË—Š‚ÌƒŞƒÃƒö" character varying(50)
  , "ˆË—Š‚ÌƒØƒåÛƒŞƒØ" character varying(50)
  , "ØÖ“ú" character varying(50)
  , "ï•éÒSKU" character varying(50)
  , "FNSKU" character varying(50)
  , "¤•é‚ÌƒØƒåÛƒŞƒØ" character varying(50)
  , "ˆË—Š‚µ‚½”" character varying(50)
  , "ƒÌƒƒƒ“ƒÚƒ‹‚µ‚½”" character varying(50)
  , "”ğŠü‚µ‚½”" character varying(50)
  , "”­‘—‚µ‚½”" character varying(50)
  , "ˆ—’†‚Ì”" character varying(50)
  , "•Ô‘—/”ğŠüè”—¿" character varying(50)
  , "’Ê‰İ" character varying(50)
  , "“Ø•ÜID" character varying(20)
  , "“ï˜Ş“ú" character varying(20)
  , "ØÖ“ú" character varying(20)
);