create table public."IPT_ƒòƒ×ƒìƒØƒŒƒüÛƒç-2" (
  "“ú•ô" character varying(20)
  , "’•¶¤•é”„ã" character varying(20)
  , "’•¶¤•é”„ã-B2B" character varying(20)
  , "’•¶‚³‚ê‚½¤•é“ß”" character varying(20)
  , "’•¶‚³‚ê‚½¤•é“ß” - B2B" character varying(20)
  , "’•¶•é–Ú‘”" character varying(20)
  , "’•¶•é–Ú‘” - B2B" character varying(20)
  , "•Ô‹à‚³‚ê‚½ƒ†ƒêƒâƒç" character varying(20)
  , "•Ô‹à—¦" character varying(20)
  , "ó‚¯æ‚Á‚½•İ‰¿" character varying(20)
  , "ó‚¯æ‚Á‚½’á•İ‰¿" character varying(20)
  , "ó‚¯æ‚Á‚½’á•İ‰¿‚ÌŠ„‡" character varying(20)
  , "³”ÆÏ‚İ‚ÌAmazonƒıÛƒĞƒâƒçƒöƒŒƒÃƒØ•ÛØÜ¿" character varying(20)
  , "¿‹Šú" character varying(20)
  , "“Ø•ÜID" character varying(20)
  , "“ï˜Ş“ú" character varying(20)
  , "ØÖ“ú" character varying(20)
);