create table public."IPT_ƒòƒ×ƒìƒØƒŒƒüÛƒç-3" (
  "“ú•ô" character varying(20)
  , "’•¶¤•é”„ã" character varying(20)
  , "’•¶¤•é”„ã-B2B" character varying(20)
  , "’•¶‚³‚ê‚½¤•é“ß”" character varying(20)
  , "’•¶‚³‚ê‚½¤•é“ß” - B2B" character varying(20)
  , "’•¶•é–Ú‘”" character varying(20)
  , "’•¶•é–Ú‘” - B2B" character varying(20)
  , "ƒùÛƒ×ƒòƒ…Û - ‡Œö" character varying(20)
  , "ƒùÛƒ×ƒòƒ…Û”-‡Œö-B2B" character varying(20)
  , "ƒÚƒâƒÖƒ‡ƒ“ - ‡Œö" character varying(20)
  , "ƒÚƒâƒÖƒ‡ƒ“-‡Œö-B2B" character varying(20)
  , "‚¨‚·‚·‚ß¤•é(ƒÖƒ‡ƒâƒóƒ“ƒÏƒÊÛƒçƒûƒâƒÎƒØ)1‚Ì" character varying(20)
  , "‚¨‚·‚·‚ß¤•é(ƒÖƒ‡ƒâƒóƒ“ƒÏƒÊÛƒçƒûƒâƒÎƒØ)2‚Ì" character varying(20)
  , "ƒ†ƒêƒâƒçƒÚƒâƒÖƒ‡ƒ“—¦" character varying(20)
  , "ƒ†ƒêƒâƒçƒÚƒâƒÖƒ‡ƒ“—¦ - B2B" character varying(20)
  , "•½‹Ïï•é”" character varying(20)
  , "å¤•é‚Ì•½‹Ï" character varying(20)
  , "“Ø•ÜID" character varying(20)
  , "“ï˜Ş“ú" character varying(20)
  , "ØÖ“ú" character varying(20)
);