create table public."IPT_ƒùƒÃƒƒ“ƒçî•ñ" (
  "“ú•ô/ŠÔ" character varying(50)
  , "ŒˆÏ”Ô†" character varying(50)
  , "ƒçƒ‰ƒ“ƒÕƒÎƒÖƒ‡ƒ“‚Ìí—Ş" character varying(50)
  , "’•¶”Ô†" character varying(50)
  , "SKU" character varying(50)
  , "à–¾" character varying(200)
  , "”—Ê" character varying(50)
  , "Amazon ï•éƒÔÛƒòƒØ" character varying(50)
  , "ƒôƒ‹ƒôƒÂƒ‹ƒƒ“ƒç1" character varying(50)
  , "ó’¬‘º1" character varying(50)
  , "“ó“¹•ûŒ§1" character varying(50)
  , "—Ø•Ö”Ô†1" character varying(50)
  , "Å‹à’¥ûŒŞ1" character varying(50)
  , "¤•é”„ã1" character varying(50)
  , "¤•é‚Ì”„ãÅ" character varying(50)
  , "”ú‘——¿" character varying(50)
  , "”ú‘——¿‚ÌÅ‹à" character varying(50)
  , "ƒÍƒôƒç•ï‘•è”—¿" character varying(50)
  , "ƒÍƒôƒç•ï‘•ƒÎƒŒƒ×ƒâƒç‚ÌÅ‹à" character varying(50)
  , "Amazon1ƒüƒÃƒ“ƒç‚Ì”ï—ğ" character varying(50)
  , "ƒöƒƒ‚ÛƒÖƒ‡ƒ“Š„ˆøŠú" character varying(50)
  , "ƒöƒƒ‚ÛƒÖƒ‡ƒ“Š„ˆø‚ÌÅ‹à" character varying(50)
  , "Œ¹ò’¥ûÅ‚ğ”º‚¤ƒıÛƒĞƒâƒçƒöƒŒƒÃƒØ" character varying(50)
  , "è”—¿" character varying(50)
  , "FBA è”—¿1" character varying(50)
  , "ƒçƒ‰ƒ“ƒÕƒÎƒÖƒ‡ƒ“‚ÉŠÖ‚·‚é‚»‚Ì‘¼‚Ìè”—¿" character varying(50)
  , "‚»‚Ì‘¼" character varying(50)
  , "‡Œö" character varying(50)
  , "Amazon2 ï•éƒÔÛƒòƒØ" character varying(50)
  , "ƒôƒ‹ƒôƒÂƒ‹ƒƒ“ƒç2" character varying(50)
  , "ó’¬‘º2" character varying(50)
  , "“ó“¹•ûŒ§2" character varying(50)
  , "—Ø•Ö”Ô†2" character varying(50)
  , "Å‹à’¥ûŒŞ" character varying(50)
  , "¤•é”„ã" character varying(50)
  , "¤•é‚Ì”„ãÅ2" character varying(50)
  , "”ú‘——¿2" character varying(50)
  , "”ú‘——¿‚ÌÅ‹à2" character varying(50)
  , "ƒÍƒôƒç•ï‘•è”—¿2" character varying(50)
  , "ƒÍƒôƒç•ï‘•ƒÎƒŒƒ×ƒâƒç‚ÌÅ‹à2" character varying(50)
  , "Amazon3ƒüƒÃƒ“ƒç‚Ì”ï—ğ " character varying(50)
  , "ƒöƒƒ‚ÛƒÖƒ‡ƒ“Š„ˆøŠú2" character varying(50)
  , "ƒöƒƒ‚ÛƒÖƒ‡ƒ“Š„ˆø‚ÌÅ‹à2" character varying(50)
  , "Œ¹ò’¥ûÅ‚ğ”º‚¤ƒıÛƒĞƒâƒçƒöƒŒƒÃƒØ2" character varying(50)
  , "è”—¿2" character varying(50)
  , "FBA è”—¿" character varying(50)
  , "ƒçƒ‰ƒ“ƒÕƒÎƒÖƒ‡ƒ“‚ÉŠÖ‚·‚é‚»‚Ì‘¼‚Ìè”—¿2" character varying(50)
  , "‚»‚Ì‘¼2" character varying(50)
  , "‡Œö2" character varying(50)
  , "“Ø•ÜID" character varying(50)
  , "“ï˜Ş“ú" character varying(20)
  , "ØÖ“ú" character varying(20)
);