create table public."IPT_ï‰×î•ñ" (
  "ï‰×“ú" character varying(50)
  , "ï•éÒSKU" character varying(50)
  , "FNSKU" character varying(50)
  , "ASIN" character varying(50)
  , "FC" character varying(50)
  , "”—Ê" character varying(50)
  , "Amazon’•¶”Ô†" character varying(50)
  , "’Ê‰İ" character varying(50)
  , "¤•é‹àŠúé¤•é1“ß‚²‚Æê" character varying(50)
  , "”ú‘——¿" character varying(50)
  , "ƒÍƒôƒç•ï‘•è”—¿" character varying(50)
  , "”ú‘—æéó‹æ’¬‘ºê" character varying(200)
  , "“ó“¹•ûŒ§–¼" character varying(200)
  , "”ú‘—æé—Ø•Ö”Ô†ê" character varying(50)
  , "•ô—Ş‚³‚ê‚½Amazon ƒüƒÃƒ“ƒç" character varying(50)
  , "“Ø•ÜID" character varying(20)
  , "“ï˜Ş“ú" character varying(20)
  , "ØÖ“ú" character varying(20)
);