create table public."IPT_è”—¿Œ©Ï‚èŠúî•ñ" (
  sku character varying(50)
  , fnsku character varying(50)
  , asin character varying(50)
  , "¤•é–¼" character varying(200)
  , "¤•éƒÏƒ‹Ûƒö" character varying(50)
  , "ƒõƒ‰ƒ“ƒè" character varying(50)
  , "ƒôƒ‹ƒôƒÂƒ‹ƒƒ“ƒç" character varying(50)
  , "‰¿Šé" character varying(20)
  , "”Ì”„‰¿Šé" character varying(50)
  , "ˆê”Ô’·‚¢•Ó" character varying(50)
  , "’†ŠÔ‚Ì•Ó" character varying(50)
  , "ˆê”Ô’Ú‚¢•Ó" character varying(50)
  , "’·‚³‚ÆüˆÍ‚Ì¡–À" character varying(50)
  , "¤•é‚Ì¡–À" character varying(50)
  , "¤•éƒğƒâƒĞÛƒ×‚Ìä—Ê" character varying(50)
  , "¤•éä—Ê" character varying(50)
  , "’Ê‰İ" character varying(50)
  , "è”—¿Œ©Ï‚èŠú" character varying(50)
  , "”Ì”„è”—¿Œ©Ï‚èŠú(ŒÂ”‚ ‚½‚è)" character varying(50)
  , "ƒÊƒåƒÓƒŠÛ•Ê¬–ñ—¿Œ©Ï‚èŠú" character varying(50)
  , "ï‰×ì‹Æè”—¿Œ©Ï‚èŠúéŒÂ”‚ ‚½‚èê" character varying(50)
  , "”­‘—ä—Êè”—¿‚ÌŒ©Ï‚èŠúéŒÂ”‚ ‚½‚èê" character varying(50)
  , "”ú‘—‘ãóè”—¿Œ©Ï‚èŠúéŒÂ”‚ ‚½‚èê" character varying(50)
  , "¡Œã‚Ìè”—¿Œ©Ï‚èŠúéŒ»İ‚ÌAmazonï•éƒÔÛƒò" character varying(50)
  , "¡Œã‚Ìï‰×ì‹Æè”—¿‚ÌŒ©Ï‚èŠúéŒÂ”‚ ‚½‚è" character varying(50)
  , "¡Œã‚Ì”­‘—ä—Êè”—¿Œ©Ï‚èŠúéŒÂ”‚ ‚½‚èê" character varying(50)
  , "¡Œã‚Ì”ú‘—‘ãóè”—¿éŒÂ”‚ ‚½‚èê" character varying(50)
  , "“Ø•ÜID" character varying(50)
  , "“ï˜Ş“ú" character varying(50)
  , "ØÖ“ú" character varying(50)
);