create table public."IPT_•Ô‘—„§î•ñ" (
  "“ú•ô" character varying(50)
  , "ï•éÒSKU" character varying(50)
  , "FNSKU" character varying(50)
  , "ASIN" character varying(50)
  , "¤•é–¼" character varying(200)
  , "ƒÒƒ“ƒæƒÂƒÖƒ‡ƒ“" character varying(50)
  , "”Ì”„‰Â”Ü‚ÈİŒÉ‚Ì‡Œö" character varying(50)
  , "•ÛŠÇ“ú”271-365“ú‚Ì”Ì”„‰Â”Ü‚ÈİŒÉ”" character varying(50)
  , "•ÛŠÇ“ú”365“úˆÈã‚Ì”Ì”„‰Â”Ü‚ÈİŒÉ”" character varying(50)
  , "”Ì”„‰Â”Ü¤•é‚ğíœ" character varying(50)
  , "”Ì”„•ó‰ÂİŒÉ‚Ì‡Œö" character varying(50)
  , "7“úŠÔ‚ªŒï‰ß‚µ‚½ï‰×•ó‰ÂİŒÉ" character varying(50)
  , "8-60“úŠÔ‚ªŒï‰ß‚µ‚½ï‰×•ó‰ÂİŒÉ" character varying(50)
  , "61-90“úŠÔ‚ªŒï‰ß‚µ‚½ï‰×•ó‰ÂİŒÉ" character varying(50)
  , "121à180“ú‚ªŒï‰ß‚µ‚½”Ì”„‰Â”Ü‚ÈİŒÉ”" character varying(50)
  , "181à270“ú‚ªŒï‰ß‚µ‚½”Ì”„‰Â”Ü‚ÈİŒÉ”" character varying(50)
  , "“Ø•ÜID" character varying(20)
  , "“ï˜Ş“ú" character varying(20)
  , "ØÖ“ú" character varying(20)
);