create table public."IPT_ƒòƒ×ƒìƒØƒŒƒüÛƒç-4" (
  "(å) ASIN" character varying(50)
  , "(ñ) ASIN" character varying(50)
  , "ƒŞƒÃƒçƒ‹" character varying(500)
  , "SKU" character varying(50)
  , "ƒÚƒâƒÖƒ‡ƒ“ - ‡Œö" character varying(50)
  , "ƒÚƒâƒÖƒ‡ƒ“-‡Œö-B2B" character varying(50)
  , "ƒÚƒâƒÖƒ‡ƒ“—¦ - ‡Œö" character varying(50)
  , "ƒÚƒâƒÖƒ‡ƒ“—¦ - ‡ŒöÛB2B" character varying(50)
  , "ƒùÛƒ×ƒòƒ…Û - ‡Œö" character varying(50)
  , "ƒùÛƒ×ƒòƒ…Û”-‡Œö-B2B" character varying(50)
  , "ƒùÛƒ×ƒòƒ…Û—¦ - ‡Œö" character varying(50)
  , "ƒùÛƒ×ƒòƒ…Û—¦ - ‡ŒöİB2B" character varying(50)
  , "‚¨‚·‚·‚ß¤•é(ƒÖƒ‡ƒâƒóƒ“ƒÏƒÊÛƒçƒûƒâƒÎƒØ1)‚Ì" character varying(50)
  , "‚¨‚·‚·‚ß¤•é(ƒÖƒ‡ƒâƒóƒ“ƒÏƒÊÛƒçƒûƒâƒÎƒØ2)‚Ì" character varying(50)
  , "’•¶‚³‚ê‚½¤•é“ß”" character varying(50)
  , "’•¶‚³‚ê‚½¤•é“ß” - B2B" character varying(50)
  , "ƒ†ƒêƒâƒçƒÚƒâƒÖƒ‡ƒ“—¦" character varying(50)
  , "ƒ†ƒêƒâƒçƒÚƒâƒÖƒ‡ƒ“—¦ - B2B" character varying(50)
  , "’•¶¤•é”„ã" character varying(50)
  , "’•¶¤•é”„ã-B2B" character varying(50)
  , "’•¶•é–Ú‘”" character varying(50)
  , "’•¶•é–Ú‘” - B2B" character varying(50)
  , "“Ø•ÜID" character varying(20)
  , "“ï˜Ş“ú" character varying(20)
  , "ØÖ“ú" character varying(20)
);